name: Run Pytest with Coverage and HTML Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with Coverage and HTML Report
      run: |
        pytest --cov=. --cov-report=term --cov-report=html --html=report.html

    - name: Upload HTML Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: html-coverage-report
        path: htmlcov/

    - name: Upload Pytest HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-html-report
        path: report.html
