name: Run Pytest with Coverage and HTML Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # change to '3.12' if 3.13 causes issues

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with Coverage and HTML report
      run: |
        pytest --cov=. --cov-report=html --html=report.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: htmlcov/

    - name: Upload Pytest HTML report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: report.html
